# Copyright © 2021, United States Government, as represented by the Administrator of the 
# National Aeronautics and Space Administration. All rights reserved.
#
# The “ISAAC - Integrated System for Autonomous and Adaptive Caretaking platform” software is 
# licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. 
#
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the 
# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
# either express or implied. See the License for the specific language governing 
# permissions and limitations under the License.
#
# ----------------------------------------------------------------------------------------------------
# NASA ISAAC User Interface
# No ROS Master launched, already provided by user
# ----------------------------------------------------------------------------------------------------
#
version: '2.1'
services:
  idi_frontend:
    # This service serves the static content that represents
    # the frontend ISAAC data interface.
    #
    image: isaac_data_interface_frontend
    build: './frontend'
    hostname: idi_frontend
    container_name: idi_frontend
    ports:
      - '8080:8080'
    networks:
      - isaac
    # uncomment the two lines below ONLY if you are actively developing
    # the IDI frontend and need fast reloads on code changes
    # volumes:
    #   - './frontend:/app:ro'

  idi_backend:
    # This service serves the front-end by providing it with
    # historical telemetry that it retrieves from ROS bridge.
    #
    image: isaac_data_interface_backend
    build: './backend'
    hostname: idi_backend
    container_name: idi_backend
    command: python /main.py
    volumes:
      - './config.json:/config.json:ro'
    depends_on:
      - rosbridge
      - idi_arangodb
    expose:
      - 9091
    links:
      - idi_arangodb
    networks:
      - isaac

  idi_arangodb:
    # This service provides a NoSQL database for the ISAAC UI. The
    # backend uses this database to store ROS messages in JSON format.
    #
    image: arangodb:latest
    hostname: idi_arangodb
    container_name: idi_arangodb
    environment:
      ARANGO_ROOT_PASSWORD: isaac
    expose:
      - 8529
    volumes:
      - arangodb_data_container:/data/arangodb3
      - arangodb_apps_data_container:/data/arangodb3-apps
    networks:
      - isaac

  rosbridge:
    # This service will provide a bridge between ROS nodes and the 
    # frontend subsystem through a WebSocket open on port 9090. 
    #
    # The backend subsystem uses this service to retrieve 
    # JSON-formatted ROS messages and store these messages
    # in the JSON-based database subsystem.
    #
    # For more info, see:
    # http://wiki.ros.org/rosbridge_suite
    # http://wiki.ros.org/web_video_server
    #
    image: isaac_data_interface_rosbridge
    build: './rosbridge'
    hostname: rosbridge
    container_name: rosbridge
    entrypoint: '/ros_entrypoint.sh'
    command: 'roslaunch --wait /rosbridge/publishers.launch'
    expose:
      - 9090
      - 8080
    environment:
      - ROS_MASTER_URI=http://172.19.0.1:11311
      - ROS_IP=172.19.0.99
    networks:
      isaac:
        ipv4_address: 172.19.0.99

# ----------------------------------------------------------------------------------------------------
# Docker Compose Volumes
# ----------------------------------------------------------------------------------------------------
volumes:
  idi_database_volume:
  arangodb_data_container:
  arangodb_apps_data_container:

# ----------------------------------------------------------------------------------------------------
# Docker Compose Networks
# ----------------------------------------------------------------------------------------------------
networks:
  isaac:
    name: isaac
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1